mysql <<EOFMYSQL
use mathursb;
SHOW TABLES;

DESC Restaurant;
DESC Dish;
Desc MenuItem;
Desc FoodOrder;

SHOW CREATE TABLE Restaurant;
SHOW CREATE TABLE Dish;
SHOW CREATE TABLE MenuItem;
SHOW CREATE TABLE FoodOrder;

SELECT COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_COLUMN_NAME, REFERENCED_TABLE_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE REFERENCED_COLUMN_NAME IS NOT NULL AND CONSTRAINT_SCHEMA = 'kmorovat';

SELECT * FROM Restaurant;
SELECT * FROM Dish;
SELECT * FROM MenuItem;
SELECT * FROM FoodOrder;

EOFMYSQL
